#view resolver
spring.mvc.view.prefix: /WEB-INF/jsp/
spring.mvc.view.suffix: .jsp

#logging
logging.path=/home1/irteam/logs/tomcat/
logging.file=/home1/irteam/logs/tomcat/spring-boot-test.log
logging.level.org.mybatis=DEBUG
logging.level.com.naver.test.notice.mapper.NoticeMapper=DEBUG
logging.level.com.naver.test.user.mapper.UserMapper=DEBUG

#Internationalization
spring.messages.basename=properties/messages
spring.messages.encoding=UTF-8
spring.messages.cache-duration=3600

#application variables
application.message: Hello LeeJeongWha

#github token
github.api.token: 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