SET DATABASE SQL SYNTAX MYS TRUE

CREATE TABLE IF NOT EXISTS school_user ( 
	id int GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) not null primary key,
 	name varchar(40) NOT NULL,
 	birth_date Date NOT NULL,
 	role varchar(40) NOT NULL,
 	subject_id int,
 	UNIQUE (name, role)
);

CREATE TABLE IF NOT EXISTS subject ( 
	id int GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) not null primary key,
 	subject_name varchar(40) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS grade ( 
	id int GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) not null primary key,
 	user_id int NOT NULL,
 	subject_id int NOT NULL,
 	score int,
 	FOREIGN KEY (user_id) REFERENCES school_user(id),
 	FOREIGN KEY (subject_id) REFERENCES subject(id)
);

INSERT INTO school_user (name, birth_date, role, subject_id) VALUES ('이정화', '1931-08-28', 'FACULTY', null);
INSERT INTO school_user (name, birth_date, role, subject_id) VALUES ('권석민', '1979-12-05', 'STUDENT', null);
INSERT INTO school_user (name, birth_date, role, subject_id) VALUES ('김도영', '1923-04-24', 'TEACHER', 1);
INSERT INTO school_user (name, birth_date, role, subject_id) VALUES ('김현철', '1974-04-24', 'TEACHER', 2);
INSERT INTO school_user (name, birth_date, role, subject_id) VALUES ('박다솔', '1995-04-24', 'STUDENT', null);

INSERT INTO subject (subject_name) VALUES ('수학');
INSERT INTO subject (subject_name) VALUES ('과학');
INSERT INTO subject (subject_name) VALUES ('국어');
INSERT INTO subject (subject_name) VALUES ('영어');

INSERT INTO grade (user_id, subject_id, score) VALUES (2, 1, 60);
INSERT INTO grade (user_id, subject_id, score) VALUES (2, 2, 90);
INSERT INTO grade (user_id, subject_id, score) VALUES (2, 3, 20);
INSERT INTO grade (user_id, subject_id, score) VALUES (5, 4, 50);